environment:
  matrix:
    - nodejs_version: 4
    - nodejs_version: 6
    - nodejs_version: 8
    - nodejs_version: 9
install:
  - ps: Install-Product node $env:nodejs_version
  - npm set fetch-retry-maxtimeout 180000
  - set PNPM_VERSION=1.23.2
  - curl -L https://unpkg.com/@pnpm/self-installer | node
  # Testing whether pnpm can upgrade itself
  - pnpm i -g pnpm@next
  - pnpm -v
  - pnpm install
matrix:
  fast_finish: true
build: off
version: '{build}'
test_script:
  - node --version
  - npm --version
  - npm t
